spring: #???? ??
  datasource: #???? 2?
    driver-class-name: com.mysql.cj.jdbc.Driver #???? 4?
    url: jdbc:mysql://localhost:3306/toytwitter?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8 #???? 4?
    username: root #???? 4?
    password: codnjsl10! #???? 4?

  jpa: #???? 2?
    hibernate: #???? 4?
      ddl-auto: create #???? 6?
    generate-ddl: true #???? 4?
    show-sql: true #???? 4?
    #open-in-view: false

